server {
    listen 80;
    server_name _;

    root /var/www/orderfe;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Proxy /api/ → nginx-lb (sama seperti vm-fe → vm-lb di production)
    location /api/ {
        proxy_pass http://nginx-lb:80/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
    }
}
